#!/bin/bash

__debug()
{
    if [[ -n ${BASH_COMP_DEBUG_FILE} ]]; then
        echo "$*" >> "${BASH_COMP_DEBUG_FILE}"
    fi
}

# Homebrew on Macs have version 1.3 of bash-completion which doesn't include
# _init_completion. This is a very minimal version of that function.
__my_init_completion()
{
    COMPREPLY=()
    _get_comp_words_by_ref cur prev words cword
}

__index_of_word()
{
    local w word=$1
    shift
    index=0
    for w in "$@"; do
        [[ $w = "$word" ]] && return
        index=$((index+1))
    done
    index=-1
}

__contains_word()
{
    local w word=$1; shift
    for w in "$@"; do
        [[ $w = "$word" ]] && return
    done
    return 1
}

__handle_reply()
{
    __debug "${FUNCNAME}"
    case $cur in
        -*)
            if [[ $(type -t compopt) = "builtin" ]]; then
                compopt -o nospace
            fi
            local allflags
            if [ ${#must_have_one_flag[@]} -ne 0 ]; then
                allflags=("${must_have_one_flag[@]}")
            else
                allflags=("${flags[*]} ${two_word_flags[*]}")
            fi
            COMPREPLY=( $(compgen -W "${allflags[*]}" -- "$cur") )
            if [[ $(type -t compopt) = "builtin" ]]; then
                [[ $COMPREPLY == *= ]] || compopt +o nospace
            fi
            return 0;
            ;;
    esac

    # check if we are handling a flag with special work handling
    local index
    __index_of_word "${prev}" "${flags_with_completion[@]}"
    if [[ ${index} -ge 0 ]]; then
        ${flags_completion[${index}]}
        return
    fi

    # we are parsing a flag and don't have a special handler, no completion
    if [[ ${cur} != "${words[cword]}" ]]; then
        return
    fi

    local completions
    if [[ ${#must_have_one_flag[@]} -ne 0 ]]; then
        completions=("${must_have_one_flag[@]}")
    elif [[ ${#must_have_one_noun[@]} -ne 0 ]]; then
        completions=("${must_have_one_noun[@]}")
    else
        completions=("${commands[@]}")
    fi
    COMPREPLY=( $(compgen -W "${completions[*]}" -- "$cur") )

    if [[ ${#COMPREPLY[@]} -eq 0 ]]; then
        declare -F __custom_func >/dev/null && __custom_func
    fi
}

# The arguments should be in the form "ext1|ext2|extn"
__handle_filename_extension_flag()
{
    local ext="$1"
    _filedir "@(${ext})"
}

__handle_subdirs_in_dir_flag()
{
    local dir="$1"
    pushd "${dir}" >/dev/null 2>&1 && _filedir -d && popd >/dev/null 2>&1
}

__handle_flag()
{
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"

    # if a command required a flag, and we found it, unset must_have_one_flag()
    local flagname=${words[c]}
    local flagvalue
    # if the word contained an =
    if [[ ${words[c]} == *"="* ]]; then
        flagvalue=${flagname#*=} # take in as flagvalue after the =
        flagname=${flagname%=*} # strip everything after the =
        flagname="${flagname}=" # but put the = back
    fi
    __debug "${FUNCNAME}: looking for ${flagname}"
    if __contains_word "${flagname}" "${must_have_one_flag[@]}"; then
        must_have_one_flag=()
    fi

    # keep flag value with flagname as flaghash
    if [ ${flagvalue} ] ; then
	flaghash[${flagname}]=${flagvalue}
    elif [ ${words[ $((c+1)) ]} ] ; then
	flaghash[${flagname}]=${words[ $((c+1)) ]}
    else
	flaghash[${flagname}]="true" # pad "true" for bool flag
    fi

    # skip the argument to a two word flag
    if __contains_word "${words[c]}" "${two_word_flags[@]}"; then
        c=$((c+1))
        # if we are looking for a flags value, don't show commands
        if [[ $c -eq $cword ]]; then
            commands=()
        fi
    fi

    c=$((c+1))

}

__handle_noun()
{
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"

    if __contains_word "${words[c]}" "${must_have_one_noun[@]}"; then
        must_have_one_noun=()
    fi

    nouns+=("${words[c]}")
    c=$((c+1))
}

__handle_command()
{
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"

    local next_command
    if [[ -n ${last_command} ]]; then
        next_command="_${last_command}_${words[c]}"
    else
        next_command="_${words[c]}"
    fi
    c=$((c+1))
    __debug "${FUNCNAME}: looking for ${next_command}"
    declare -F $next_command >/dev/null && $next_command
}

__handle_word()
{
    if [[ $c -ge $cword ]]; then
        __handle_reply
        return
    fi
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"
    if [[ "${words[c]}" == -* ]]; then
        __handle_flag
    elif __contains_word "${words[c]}" "${commands[@]}"; then
        __handle_command
    else
        __handle_noun
    fi
    __handle_word
}


__kubernetes-manifest-scanner_itemlister()
{
    local itemlist_out

    if [ ! -z "${flaghash["-f"]}" ] ; then
        itemlist_out=$(kubernetes-manifest-scanner itemlist -f ${flaghash["-f"]} 2>/dev/null)
	if [ ! -z "${flaghash["-k"]}" -o ! -z "${flaghash["--insecure="]}" ] ; then
            itemlist_out=$(kubernetes-manifest-scanner itemlist -k -f ${flaghash["-f"]} 2>/dev/null)
	fi
    elif [ ! -z "${flaghash["--filename="]}" ] ; then
        itemlist_out=$(kubernetes-manifest-scanner itemlist --filename=${flaghash["--filename="]} 2>/dev/null)
	if [ ! -z "${flaghash["-k"]}" -o ! -z "${flaghash["--insecure="]}" ] ; then
        itemlist_out=$(kubernetes-manifest-scanner itemlist -k --filename=${flaghash["--filename="]} 2>/dev/null)
	fi
    else
        itemlist_out=$(kubernetes-manifest-scanner itemlist 2>/dev/null)
    fi

    if [ ! -z "${itemlist_out}" ] ; then
        COMPREPLY=( $( compgen -W "${itemlist_out[*]}" -- "$cur" ) )
    fi
}

__custom_func() {
    case ${last_command} in

        kubernetes-manifest-scanner_sample)
           __kubernetes-manifest-scanner_itemlister $1
           return
            ;;
        *)
            ;;
    esac
}

_kubernetes-manifest-scanner_sample()
{
    last_command="kubernetes-manifest-scanner_sample"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--depth=")
    two_word_flags+=("-d")
    flags+=("--filename=")
    two_word_flags+=("-f")
    flags+=("--item=")
    two_word_flags+=("-i")
    flags+=("--log-flush-frequency=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_kubernetes-manifest-scanner_snippet()
{
    last_command="kubernetes-manifest-scanner_snippet"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--filename=")
    two_word_flags+=("-f")
    flags+=("--item=")
    two_word_flags+=("-i")
    flags+=("--log-flush-frequency=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_kubernetes-manifest-scanner_itemlist()
{
    last_command="kubernetes-manifest-scanner_itemlist"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--filename=")
    two_word_flags+=("-f")
    flags+=("--log-flush-frequency=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_kubernetes-manifest-scanner()
{
    last_command="kubernetes-manifest-scanner"
    commands=()
    commands+=("sample")
    commands+=("snippet")
    commands+=("itemlist")

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--log-flush-frequency=")

    must_have_one_flag=()
    must_have_one_noun=()
}

__start_kubernetes-manifest-scanner()
{
    local cur prev words cword
    declare -A flaghash
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion -s || return
    else
        __my_init_completion || return
    fi

    local c=0
    local flags=()
    local two_word_flags=()
    local flags_with_completion=()
    local flags_completion=()
    local commands=("kubernetes-manifest-scanner")
    local must_have_one_flag=()
    local must_have_one_noun=()
    local last_command
    local nouns=()

    __handle_word
}

if [[ $(type -t compopt) = "builtin" ]]; then
    complete -F __start_kubernetes-manifest-scanner kubernetes-manifest-scanner
else
    complete -o nospace -F __start_kubernetes-manifest-scanner kubernetes-manifest-scanner
fi

COMP_WORDBREAKS=${COMP_WORDBREAKS//:}

# ex: ts=4 sw=4 et filetype=sh
